### ISSUE TITLE
Linux stop button fails.

### ISSUE THREAD

**Issue by MahdiRahbar** [mir-am/LIBTwinSVM#1]

**Comment by mir-am** [comment]
I could not reproduce this issue on my Linux system.
I think the issue can be solved by updating the dependencies of the library to the latest version (Especially the PyQT.).
I may close the issue.

**Comment by mir-am** [comment]
I could not reproduce this issue on my Linux system.
I think the issue can be solved by updating the dependencies of the library to the latest version (Especially the PyQT.).
I may close the issue.
