### ISSUE TITLE
cannot import name 'clipdcd' from 'libtsvm.optimizer'

### ISSUE THREAD

**Issue by laulliam** [mir-am/LIBTwinSVM#9]

**Comment by mir-am** [comment]
Thanks for creating an issue.
I would appreciate it if you could provide more info about your Python version, OS, stack trace, etc.
Now, it is difficult to guess why `clipdcd` cannot be imported.

**Comment by laulliam** [comment]
@mir-am Thanks for your reply.
I meet this problem when install from source code.
But now I can use it by `pip3 install libtwinsvm`.
